name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Format
        run: pnpm run format

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm run lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup nix
        uses: cachix/install-nix-action@v31
      - name: Setup cachix
        uses: cachix/cachix-action@v16
        with:
          name: toino
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: ags,nix-community
      # Workaround for ags changing the tsconfig f
      - name: Backup tsconfig
        run: cp tsconfig.json tsconfig.json.bak
      - name: Install ags
        run: nix develop --command ags types --directory . --update
      - name: Restore tsconfig
        run: mv tsconfig.json.bak tsconfig.json
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Typecheck
        run: pnpm run check

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup nix
        uses: cachix/install-nix-action@v31
      - name: Setup cachix
        uses: cachix/cachix-action@v16
        with:
          name: toino
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: ags,nix-community
      - name: Build
        run: nix build
