name: Upgrade packages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  upgrade:
    name: Upgrade packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Nix
        uses: cachix/install-nix-action@v31
      - name: Upgrade dependencies
        uses: DeterminateSystems/update-flake-lock@v27
